[package]
name = "triehash-ethereum"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trie-root helpers, ethereum style"
license = "GPL-3.0"

[dependencies]
#triehash = { version = "0.3.0", features = ["ethereum"] }
triehash = { git = "https://github.com/cheme/parity-common.git", branch = "use-trie", features = ["ethereum"] }
ethereum-types = "0.4"
keccak-hasher = { path = "../keccak-hasher" }
