[package]
name = "patricia-trie"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
hashdb = { git = "https://github.com/paritytech/parity-common" }
heapsize = "0.4"
log = "0.3"
rand = "0.4"

[dev-dependencies]
env_logger = "0.5"
ethereum-types = "0.3"
keccak-hash = { git = "https://github.com/paritytech/parity-common" }
keccak-hasher = { path = "../keccak-hasher" }
memorydb = { git = "https://github.com/paritytech/parity-common" }
patricia-trie-ethereum = { path = "../patricia-trie-ethereum" }
rlp = { git = "https://github.com/paritytech/parity-common" }
trie-standardmap = { git = "https://github.com/paritytech/parity-common" }
triehash = { git = "https://github.com/paritytech/parity-common" }
