stages:
  - build
  - test
variables:
  GIT_DEPTH: "3"
  SIMPLECOV: "true" 
  RUST_BACKTRACE: "1"
cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
test-ci:
  stage: build
  script:
    - echo 2+2
  tags:
    - rust-test
