sudo: false
dist: trusty
language: generic
env:
  global:
  - PROJECT_NAME=parity
  - RUST_BACKTRACE="1"
cache:
  apt: true
matrix:
  include:
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=stable RUN_TESTS=true
    addons:
      apt:
        packages: &15588620
        - g++-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross
        - qemu-user
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=stable
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=stable
    addons:
      apt:
        packages: &15805720
        - build-essential
        - g++-multilib
        - libedit-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=stable
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=stable
    addons:
      apt:
        packages: &16862360
        - build-essential
        - g++
        - libedit-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=stable
    addons:
      apt:
        packages: &17344860
        - build-essential
        - g++
        - libedit-dev
        - libcurl4-openssl-dev
        - libelf-dev
        - libdw-dev
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=beta
    addons:
      apt:
        packages: *15588620
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=beta
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=beta
    addons:
      apt:
        packages: *15805720
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=beta
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=beta
    addons:
      apt:
        packages: *16862360
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=beta
    addons:
      apt:
        packages: *17344860
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=nightly
    addons:
      apt:
        packages: *15588620
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=nightly
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=nightly
    addons:
      apt:
        packages: *15805720
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=nightly
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=nightly
    addons:
      apt:
        packages: *16862360
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=nightly
    addons:
      apt:
        packages: *17344860
  allow_failures:
  - os: linux
    env: TARGET=armv7-unknown-linux-gnueabihf CHANNEL=stable
    addons:
      apt:
        packages: 
install:
- export PATH="$PATH:~/multirust/bin"
- bash ci/install.sh
script:
- bash ci/script.sh
before_deploy:
- bash ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: kIthimcXHUuM/TvzyXBZyABKK7tXvVbKcH6G3wAkZ/kg21OWwBxO0NrY6D0QG26LocZ+oUCQbJnDg56UcUTpegCOJ1zuFYTvceIduFBxP19tzYqztLIOZ5ueufnAzIl/cUOfhpaooOlxzHAPi+aJJSsxEjObwdTkYqyhgte/r8RWJUIBf2qge8+8bvdaDxsgdwR0VWYqaR2Cjo4aCWxhwpZJozKb/mbJEmg/IbhO7LyeD5Ls4gygSJBgn0TmLzPggE+DYMVvVrZNEHwuidy7+nSOjj5gjMD3Sp9ACD9Y6tiJlrFUbb7iYwGngXHyqIOKm/zGwSwn9faT409e3p9CSr+5PaVf24Jg8YFqY9uDX/8ysYRH2zt+M8a9fdWBuRkptJVUqNHVkEQZNQRsg2JKiT2a5/Jt5V3a7xf8hX5uVh9J7Mt2VoaFAZk70NWVu2VqRdGgkNELrqYeprLFteb7UT0DCbJoAvUxWeMPhO4zcomvnOTHz5PSLQ6hiAApnc21XS8rNAD2OK01BayKAntYyVVGGxvIkvNlF8Rhiem70EkZ2dFNRTp5OqlPNicE5ZuYFBMKvhAZW0QosC/m5/EYR8wgydeF7HZ8iAEmOw+hDkga/crMXJd7qwKdFcwl2paqAYTmitSzpEYx1GjCLyZ/IoKjc1DMx4midpIT7ttkFP0=
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    condition: $CHANNEL = stable
    tags: true
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
notifications:
  email:
    on_success: general.beck@gmail.com
  slack:
    secure: KmMUp0H/DOEOfXlHFqOCbLiEHkneawz9Tf+EcPbPzruixtYXrJiXAr6qRPmiAMfij6UAMGlxEOQ7VlYyRdvTU8lKHTYe8FdPQD51QVvj8HRbTi8LoVfXvN9JC8slwbwQZJ1kNG6/doZLbgIWPRR2XSOCITdHC2+Vr0mQHep68s7IJ2khJe17V8utBsDM4w0Je3uh2j+2j6w0T8JSouWp138gv36dvmBShm8o0yy7WaH1DIDnV6WmHti52vy+EiWTLeKbMS8/fFB2VzAY7Q9eFTaeuF8gV0Pau2xET8vtcCY3MPXsMILia62XkbA+8IzULr0ZOKATe6fAJG8cylccI2jI9GhIjkNpNXS+x2w93COCC7z4kXHHHDn9Cisw51vzzeXKo3tOqS4/hk7BXS9afP0swrFQUwXFIng4SpkK8nZRT788FQuvmkHdkvclv8En/NZsphdDCxUx9oLpQ/+J9wvxCXVJoM5uXuMEDvaeDCLE7kMbiEP0oTJwVKPjIVSarD+N54uGc9IiqThO3UBS52dK9x9NfvpU7uUmptoKvH9HnHRDUZKbeAx3xzn4Y29GI8B4dtgeO/I3XcqCJGjYRc+HGqyqVri7dRyQGSTYOtsgQZjUTyltwVREosSueGaQAuIC5gjkbRJPWW1OG4dAtYwFolMCkz6otcstPdPNr+Y=
