environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.9.0-x86_64-pc-windows-msvc.exe"
  - rust-1.9.0-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: off

test_script:
  - cargo test --verbose --release

after_test:
  - cargo build --verbose --release
  - \"C:\Program Files (x86)\NSIS\bin\makensis.exe\" nsis\installer.nsi

artifacts:
- path: nsis\installer.exe
  name: Windows Installer (x86_64)

cache:
  target
  c:\users\appveyor\.cargo
