[package]
description = "Parity Ethereum client"
name = "parity"
# NOTE Make sure to update util/version/Cargo.toml as well
version = "1.11.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[[bin]]
path = "parity/main.rs"
name = "parity"

[workspace]
members = [
	"chainspec",
	"dapps/js-glue",
	"ethcore/wasm/run",
	"ethcore/types",
	"ethkey/cli",
	"ethstore/cli",
	"evmbin",
	"miner",
	"transaction-pool",
	"whisper"
]

[patch.crates-io]
ring = { git = "https://github.com/paritytech/ring" }
