[package]
name = "evmbin"
description = "Parity's EVM implementation"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
ethcore = { path = "../ethcore" }
ethcore-util = { path = "../util" }
