[package]
name = "triehash"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in memory patricia trie operations"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
rlp = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3"
keccak-hash = { git = "https://github.com/paritytech/parity-common" }

[dev-dependencies]
trie-standardmap = { git = "https://github.com/paritytech/parity-common" }
