[package]
name = "rlp-std"
version = "0.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
publish = false
build = "../build.rs"

[build-dependencies]
rustc_version = "0.2.1"

[dependencies.rlp]
path = "../.."

[workspace]
members = ["."]

[[bin]]
name = "untrusted_std"
path = "untrusted_std.rs"

