[package]
name = "ethcore-store"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
dir = { path = "../../util/dir" }
ethcore-crypto = { path = "../crypto" }
ethereum-types = "0.3"
ethkey = { path = "../../ethkey" }
itertools = "0.5"
libc = "0.2"
log = "0.3"
parity-wordlist = "1.0"
parking_lot = "0.5"
rand = "0.4"
rust-crypto = "0.2.36"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.4"
subtle = "0.5"
tempdir = "0.3"
time = "0.1.34"
tiny-keccak = "1.3"

[dev-dependencies]
matches = "0.1"

[lib]
