[package]
name = "memory-cache"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "An LRU-cache which operates on memory used"
license = "GPL3"

[dependencies]
parity-util-mem = { git = "https://github.com/cheme/parity-common", branch = "mem-tools2" }
lru-cache = "0.1"
