[package]
description = "Hardware wallet support."
homepage = "http://parity.io"
license = "GPL-3.0"
name = "hardware-wallet"
version = "1.8.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.0.0"
log = "0.3"
parking_lot = "0.4"
quick-protobuf = "0.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

hidapi = { git = "https://github.com/paritytech/hidapi-rs" }
libusb = { git = "https://github.com/paritytech/libusb-rs" }

ethkey = { path = "../ethkey" }
ethcore-util = { path = "../util" }
ethcore-bigint = { path = "../util/bigint" }

[dev-dependencies]
rustc-hex = "1.0"
