[package]
description = "Parity WASM Test Run"
name = "pwasm-run-test"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
ethereum-types = "0.9"
ethjson = { path = "../../../json" }
vm = { path = "../../vm" }
wasm = { path = "../" }
clap = { git = "https://github.com/clap-rs/clap" }
env_logger = "0.7"
rustc-hex = "2.1.0"

[features]
default = ["ethereum-types/std"]
