[package]
description = "Ethcore blockchain database"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-blockchain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ethcore-db = { path = "../db" }
ansi_term = "0.10"
blooms-db = { path = "../../util/blooms-db" }
bn = { git = "https://github.com/paritytech/bn", default-features = false }
byteorder = "1.0"
common-types = { path = "../types" }
crossbeam = "0.4"
ethash = { path = "../../ethash" }
ethcore-bloom-journal = { path = "../../util/bloom" }
parity-bytes = "0.1"
hashdb = "0.3.0"
memorydb = "0.3.0"
patricia-trie = "0.3.0"
patricia-trie-ethereum = { path = "../../util/patricia-trie-ethereum" }
parity-crypto = "0.2"
error-chain = { version = "0.12", default-features = false }
ethcore-io = { path = "../../util/io" }
ethcore-logger = { path = "../../logger" }
ethcore-miner = { path = "../../miner" }
ethcore-transaction = { path = ".././transaction" }
ethereum-types = "0.4"
memory-cache = { path = "../../util/memory_cache" }
ethabi = "6.0"
ethabi-derive = "6.0"
ethabi-contract = "6.0"
ethjson = { path = "../../json" }
ethkey = { path = "../../ethkey" }
ethstore = { path = "../../ethstore" }
evm = { path = "../evm" }
heapsize = "0.4"
itertools = "0.5"
lazy_static = "1.0"
log = "0.4"
lru-cache = "0.1"
num = { version = "0.1", default-features = false, features = ["bigint"] }
num_cpus = "1.2"
parity-machine = { path = "../../machine" }
parking_lot = "0.7"
rayon = "1.0"
rand = "0.4"
rlp = { version = "0.3.0", features = ["ethereum"] }
rlp_compress = { path = "../../util/rlp_compress" }
rlp_derive = { path = "../../util/rlp_derive" }
kvdb = "0.1"
kvdb-memorydb = "0.1"
parity-snappy = "0.1"
stop-guard = { path = "../../util/stop-guard" }
macros = { path = "../../util/macros" }
rustc-hex = "1.0"
stats = { path = "../../util/stats" }
trace-time = "0.1"
using_queue = { path = "../../util/using_queue" }
vm = { path = "../vm" }
wasm = { path = "../wasm" }
keccak-hash = "0.1"
triehash-ethereum = { version = "0.2",  path = "../../util/triehash-ethereum" }
unexpected = { path = "../../util/unexpected" }
journaldb = { path = "../../util/journaldb" }
keccak-hasher = { path = "../../util/keccak-hasher" }
kvdb-rocksdb = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
len-caching-lock = { path = "../../util/len-caching-lock" }

[dev-dependencies]
env_logger = "0.5"
tempdir = "0.3"
trie-standardmap = "0.1"
criterion = "0.2"
ethcore = { path = "../", features = ["test-helpers"] }
