[package]
name = "ethcore-chain-notify"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ethcore-blockchain = { path = "../blockchain" }
ethereum-types = "0.4"
types = { path = "../types", package = "common-types" }
parity-bytes = "0.1"

