[package]
name = "ethcore-store-cli"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[[bin]]
name = "ethstore"
path = "src/main.rs"
doc = false

[dependencies]
dir = { path = '../../../util/dir' }
docopt = "0.8"
ethcore-store = { path = ".." }
num_cpus = "1.6"
panic_hook = { path = "../../../util/panic_hook" }
parking_lot = "0.5"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
tempdir = "0.3.5"
