[package]
name = "client-traits"
version = "0.1.0"
edition = "2018"


[dependencies]
ethcore-builtin = { path = "../builtin" }
call-contract = { package = "ethcore-call-contract", path = "../call-contract" }
common-types = { path = "../types" }
derive_more = "0.15.0"
ethereum-types = "0.6"
ethkey = { path = "../../accounts/ethkey" }
rlp = "0.4.0" # todo: only needed for `DecoderError` – fix
vm = { path = "../vm" }
