[package]
name = "journaldb"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "A `HashDB` which can manage a short-term journal potentially containing many forks of mutually exclusive actions"
license = "GPL3"

[dependencies]
parity-bytes = "0.1"
ethereum-types = "0.4"
hashdb = "0.3.0"
parity-util-mem = { git = "https://github.com/cheme/parity-common", branch = "deprecate_heapsize" }
keccak-hasher = { path = "../keccak-hasher" }
kvdb = "0.1"
log = "0.4"
#memorydb = "0.4"
memorydb = { git = "https://github.com/cheme/parity-common", branch = "deprecate_heapsize" }
parking_lot = "0.7"
fastmap = { path = "../../util/fastmap" }
rlp = { version = "0.3.0", features = ["ethereum"] }

[dev-dependencies]
env_logger = "0.5"
keccak-hash = "0.1"
kvdb-memorydb = "0.1"
