[package]
name = "hashdb"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trait for hash-keyed databases."
repository = "https://github.com/paritytech/parity/"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
heapsize = "0.4"